package gui;

public enum GuiStates {
	DEVELOPER,
	ATTACK, DEFENCE, STRENGTH, RANGED, MAGIC, PRAYER, SUMMONING,
	FISHING, MINING, WOODCUTTING, FARMING, HUNTER, DIVINATION,
	COOKING, SMITHING, FLETCHING, CRAFTING, HERBLORE, FIREMAKING, RUNFECRAFTING, CONSTRUCTION,
	AGILITY, SLAYER, THIEVING;

}
